<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>FBLib</AssemblyName>
    <RootNamespace>FBLib</RootNamespace>
    <OutDir>..\bin\</OutDir>
  </PropertyGroup>
</Project>
